version: '3'
services:
  db:
    image: mysql:latest
    container_name: pay-it-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3307:3306"

  tdd:
    build: .
    command: ["bundle", "exec", 'rspec', 'spec']
    environment:
      - RAILS_ENV=test
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=pay_it_test
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_POOL=${DATABASE_POOL}
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - '.env'

volumes:
  mysql_data: {}
